In [3]:
import numpy as np

Generating Initial Population Randomly

In [21]:
num_attributes = 8
levels_per_attribute = 3

population_size = 100

initial_population = np.random.randint(2, size=(population_size, num_attributes * 2))

print("Initial Population:")
print(initial_population)

Initial Population:
[[0 0 0 ... 1 0 0]
 [1 1 0 ... 1 0 1]
 [1 1 1 ... 0 0 1]
 ...
 [1 0 1 ... 1 0 1]
 [0 0 0 ... 1 1 1]
 [1 1 0 ... 0 0 1]]


In [22]:
initial_population.shape

(100, 16)

Using Dummy variable coding

In [24]:
import pandas as pd
import numpy as np

# Define categorical variables and their levels
categorical_variables = {
    'Material_Selection': ['Wood', 'Metal', 'Plastic'],
    'Pad_Arrangement': ['Circular', 'Linear', 'Grid'],
    'Touch_Sensor_Configuration': ['Single', 'Double', 'Triple'],
    'Enclosure_Color': ['Red', 'Blue', 'Black', 'White'],
    'Touch_Pad_Size': ['Small', 'Medium', 'Large'],
    'Audio_Output_Type': ['Speaker', 'Headphone_Jack', 'Bluetooth'],
    'Touch_Pad_Material': ['Conductive_Metal', 'Conductive_Polymer', 'Capacitive_Glass'],
    'Instrument_Weight': ['Light', 'Medium', 'Heavy']
}

# Define population size
population_size = 100

# Generate initial population
initial_population_dvc = []
for _ in range(population_size):
    individual = {}
    for variable, levels in categorical_variables.items():
        selected_level = np.random.choice(levels)
        for level in levels:
            individual[f'{variable}_{level}'] = 1 if selected_level == level else 0
    initial_population_dvc.append(individual)

# Convert initial population to DataFrame
initial_population_df = pd.DataFrame(initial_population_dvc)

# Display the initial population
print("Initial Population:")
print(initial_population_df)

Initial Population:
    Material_Selection_Wood  Material_Selection_Metal  \
0                         0                         1   
1                         1                         0   
2                         1                         0   
3                         1                         0   
4                         1                         0   
..                      ...                       ...   
95                        1                         0   
96                        0                         1   
97                        0                         1   
98                        1                         0   
99                        0                         1   

    Material_Selection_Plastic  Pad_Arrangement_Circular  \
0                            0                         1   
1                            0                         0   
2                            0                         1   
3                            0                         

In [25]:
initial_population_dvc

[{'Material_Selection_Wood': 0,
  'Material_Selection_Metal': 1,
  'Material_Selection_Plastic': 0,
  'Pad_Arrangement_Circular': 1,
  'Pad_Arrangement_Linear': 0,
  'Pad_Arrangement_Grid': 0,
  'Touch_Sensor_Configuration_Single': 1,
  'Touch_Sensor_Configuration_Double': 0,
  'Touch_Sensor_Configuration_Triple': 0,
  'Enclosure_Color_Red': 0,
  'Enclosure_Color_Blue': 0,
  'Enclosure_Color_Black': 0,
  'Enclosure_Color_White': 1,
  'Touch_Pad_Size_Small': 0,
  'Touch_Pad_Size_Medium': 1,
  'Touch_Pad_Size_Large': 0,
  'Audio_Output_Type_Speaker': 0,
  'Audio_Output_Type_Headphone_Jack': 0,
  'Audio_Output_Type_Bluetooth': 1,
  'Touch_Pad_Material_Conductive_Metal': 0,
  'Touch_Pad_Material_Conductive_Polymer': 1,
  'Touch_Pad_Material_Capacitive_Glass': 0,
  'Instrument_Weight_Light': 0,
  'Instrument_Weight_Medium': 0,
  'Instrument_Weight_Heavy': 1},
 {'Material_Selection_Wood': 1,
  'Material_Selection_Metal': 0,
  'Material_Selection_Plastic': 0,
  'Pad_Arrangement_Circular': 0,


Obtaining Part-Worth Utilities from Conjoint Analysis - random for now, add real values

In [26]:
# Define the number of customers (N) and size of the binary string (P)
N = 100  # Example: 100 customers
P = num_attributes * 2  # Size of the binary string representing the instrument configuration

# Define the range of values for conjoint analysis (example: -1 to 1)
conjoint_values = np.linspace(-1, 1, num=levels_per_attribute)

# Generate random conjoint analysis values for each customer and attribute
BETA = np.random.choice(conjoint_values, size=(N, P))

print("Matrix BETA (Conjoint Analysis Values):")
print(BETA)

Matrix BETA (Conjoint Analysis Values):
[[-1. -1.  1. ... -1. -1.  0.]
 [-1.  1. -1. ...  0.  1.  1.]
 [ 1.  0.  1. ...  0. -1.  0.]
 ...
 [ 1.  1.  0. ...  0. -1.  1.]
 [ 0.  1.  0. ... -1. -1.  0.]
 [ 1.  0. -1. ... -1.  0.  0.]]


Determine utility for each product by each customer from the beta matrix

In [27]:
POP = initial_population
PROD_UTIL = BETA * POP

In [28]:
PROD_UTIL.shape

(100, 16)

In [29]:
PROD_UTIL

array([[-0., -0.,  0., ..., -1., -0.,  0.],
       [-1.,  1., -0., ...,  0.,  0.,  1.],
       [ 1.,  0.,  1., ...,  0., -0.,  0.],
       ...,
       [ 1.,  0.,  0., ...,  0., -0.,  1.],
       [ 0.,  0.,  0., ..., -1., -1.,  0.],
       [ 1.,  0., -0., ..., -0.,  0.,  0.]])

In [30]:
# Define the number of customers (N) and the number of aspects of utility (P)
N = 100  # Example: 100 customers
P = 8    # Example: 8 aspects of utility

# Generate random utility values for the STATQUO matrix
STATQUO = np.random.rand(N, P)

print("STATQUO Matrix (Random Utility Values):")
print(STATQUO)

STATQUO Matrix (Random Utility Values):
[[0.31359418 0.11447227 0.29142437 0.91370537 0.94493654 0.32262438
  0.32524337 0.62810373]
 [0.44942824 0.43674787 0.0636286  0.23703592 0.39276033 0.39050607
  0.70479995 0.91989053]
 [0.56277746 0.20203658 0.14148844 0.06460826 0.05342271 0.37991195
  0.6371294  0.07928186]
 [0.39274295 0.33053879 0.74201841 0.69451673 0.42753346 0.48566063
  0.09719193 0.82321646]
 [0.70141649 0.64322261 0.67856986 0.66718672 0.83784972 0.55199114
  0.82442867 0.4115076 ]
 [0.12141168 0.08395553 0.59120474 0.93288009 0.24558033 0.47281009
  0.70458689 0.0628542 ]
 [0.03992514 0.90080831 0.34897735 0.17371212 0.75366905 0.37456434
  0.31760132 0.75857229]
 [0.30989782 0.31860494 0.46443234 0.97384523 0.39756582 0.83832716
  0.66159395 0.24677696]
 [0.91574388 0.69903528 0.75636237 0.12123928 0.51832262 0.05654284
  0.41010747 0.75338837]
 [0.87991257 0.69531821 0.92531539 0.98750426 0.6916325  0.52841411
  0.91360264 0.97406511]
 [0.02112611 0.95631049 0.5085