In [35]:
import numpy as np
import random

Generating Initial Population Randomly

In [6]:
#Global variable

num_attributes = 8
levels_per_attribute = 3

M = 100 # number of strings
P = num_attributes * 2 # we do "num_attributes * 2" since each attribute is represented using a 2-bit binary string
N = 100 # number  of customers

In [3]:
"""
num_attributes = 8
levels_per_attribute = 3

M = 100
P = num_attributes * 2 # we do "num_attributes * 2" since each attribute is represented using a 2-bit binary string

initial_population = np.random.randint(2, size=(M, P)) 

print("Initial Population:")
print(initial_population)
"""

Initial Population:
[[1 0 0 ... 0 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 1]
 [0 1 1 ... 0 0 1]]


In [4]:
#initial_population.shape

(100, 16)

Using Dummy variable coding

In [4]:
# Define the number of attributes and levels for each attribute
K = 8  # Number of attributes
L = [3, 3, 3, 3, 3, 3, 3, 3]  # Number of levels for each attribute

P = sum(L[j] - 1 for j in range(K))  # Total number of bits required for binary string representation

# Initialize the population matrix
POP = np.zeros((M, P), dtype=int)

# Generate random binary strings for each product in the population
for i in range(M):
    product_string = ''
    for j in range(K):  # Iterate over each attribute
        # Generate the binary substring for the current attribute
        attribute_string = '0' * (L[j] - 1)
        # Choose a random level for the current attribute
        level_index = np.random.randint(L[j] - 1)  # Adjusted to L[j] - 1
        # Set the corresponding bit to '1' for the chosen level
        attribute_string = attribute_string[:level_index] + '1' + attribute_string[level_index+1:]
        # Append the binary substring for the current attribute to the product string
        product_string += attribute_string
    
    # Pad the binary string with zeros if its length is less than P
    product_string += '0' * (P - len(product_string))
    
    # Convert the binary string to a numpy array and assign it to the population matrix
    POP[i] = np.array(list(product_string), dtype=int)

# Display the population matrix
print("Initial Population Matrix (POP):")
print(POP)

Initial Population Matrix (POP):
[[0 1 1 ... 0 0 1]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 1 0 1]
 ...
 [1 0 1 ... 1 1 0]
 [0 1 0 ... 1 1 0]
 [1 0 0 ... 1 0 1]]


In [5]:
POP.shape

(100, 16)

Obtaining Part-Worth Utilities from Conjoint Analysis - random for now, add real values

In [7]:
# Define the range of values for conjoint analysis (example: -1 to 1)
conjoint_values = np.linspace(-1, 1, num=levels_per_attribute)

# Generate random conjoint analysis values for each customer and attribute
BETA = np.random.choice(conjoint_values, size=(N, P))

print("Matrix BETA (Conjoint Analysis Values):")
print(BETA)

Matrix BETA (Conjoint Analysis Values):
[[ 0.  0. -1. ... -1. -1. -1.]
 [-1.  1.  0. ... -1.  1.  0.]
 [-1.  0. -1. ...  0.  0. -1.]
 ...
 [ 0.  1.  1. ...  0.  1. -1.]
 [-1. -1.  1. ... -1. -1.  0.]
 [ 1. -1. -1. ...  1.  0. -1.]]


In [8]:
BETA.shape

(100, 16)

In [9]:
STATQUO = np.random.randn(N)  # Status quo utilities vector (N)

In [10]:
STATQUO

array([ 7.23529244e-01, -8.08118284e-02,  1.34381586e-02, -2.87364144e-01,
       -8.39726207e-01,  3.94313729e-01, -6.26319013e-01, -5.87904219e-01,
       -4.70638691e-01,  7.54205297e-01,  9.67085013e-01,  8.18912963e-01,
        7.34670892e-01,  2.66770440e-01, -2.71661249e-01,  4.44161810e-01,
       -4.11964437e-01,  3.50514403e-01,  9.01958904e-01, -3.19340230e-02,
       -8.59031209e-01,  1.51315351e-01, -2.79645183e-01, -6.20237066e-01,
        1.26896102e+00, -1.18599328e+00,  1.78971059e+00, -7.06986001e-01,
       -1.02455830e+00,  1.17933814e+00,  5.63165644e-01,  1.20949965e-01,
        2.37546792e-01, -3.90793024e-01,  3.02815873e-02,  1.80716742e-02,
        2.16279209e-01,  4.09383874e-01,  1.96722997e-03,  5.87516042e-01,
        2.29050835e-02, -1.46068512e+00,  2.12903457e+00,  1.59711580e+00,
        2.99048126e-01,  8.20877873e-01, -3.38881271e-01, -4.86214487e-01,
       -4.29638054e-01, -6.81160839e-02,  1.63351067e+00, -2.70566811e-01,
        1.59537511e-01, -

In [11]:
STATQUO.shape

(100,)

Determine utility for each product by each customer from the beta matrix

In [19]:
#Helper Function for determining utility

def fitness(population):
    population_t = np.transpose(population)
    PROD_UTIL = np.dot(BETA, population_t)
    share_of_choices = np.sum(PROD_UTIL > STATQUO[:, np.newaxis], axis=0)
    fitness_values = share_of_choices / N
    return fitness_values
#    print(fitness_values)
#    print(fitness_values.shape)


#fitness(POP)

In [12]:
#POP_0 = POP
#POP_0_transposed = np.transpose(POP_0)
#POP_0_transposed.shape

(16, 100)

In [13]:
#POP_0_transposed

array([[0, 0, 1, ..., 1, 0, 1],
       [1, 1, 0, ..., 0, 1, 0],
       [1, 0, 1, ..., 1, 0, 0],
       ...,
       [0, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 0, 1]])

In [63]:
#PROD_UTIL = np.dot(BETA, POP_0_transposed)

In [64]:
#PROD_UTIL.shape

(100, 100)

In [65]:
#PROD_UTIL

array([[-3.,  1., -1., ..., -2.,  1.,  0.],
       [ 2.,  4.,  2., ...,  2.,  1.,  0.],
       [ 1., -3., -1., ...,  0., -3.,  0.],
       ...,
       [ 2.,  2., -1., ...,  2., -3., -1.],
       [-4., -1., -5., ..., -2., -6., -3.],
       [-1., -2., -4., ...,  0., -2.,  0.]])

In [67]:
#share_of_choices = np.sum(PROD_UTIL > STATQUO[:, np.newaxis], axis=0)

In [68]:
#fitness_values = share_of_choices / N

# Display the fitness values for each product
#print("Fitness values for each product:")
#print(fitness_values)

Fitness values for each product:
[0.48 0.52 0.48 0.58 0.51 0.51 0.49 0.47 0.48 0.48 0.54 0.55 0.53 0.49
 0.51 0.51 0.46 0.51 0.5  0.44 0.44 0.48 0.52 0.51 0.52 0.52 0.44 0.53
 0.51 0.44 0.48 0.5  0.53 0.45 0.51 0.49 0.55 0.48 0.49 0.53 0.51 0.51
 0.57 0.52 0.53 0.52 0.48 0.44 0.53 0.53 0.58 0.52 0.52 0.52 0.56 0.5
 0.53 0.48 0.53 0.47 0.54 0.51 0.58 0.51 0.48 0.52 0.53 0.46 0.48 0.48
 0.48 0.5  0.53 0.44 0.51 0.44 0.47 0.5  0.51 0.5  0.48 0.53 0.45 0.49
 0.54 0.52 0.49 0.54 0.53 0.52 0.53 0.49 0.47 0.49 0.51 0.51 0.45 0.48
 0.48 0.47]


In [26]:
len(POP)

100

Selection

In [48]:
def reproduction(population, fitness_values):
    # Select individuals for reproduction based on their fitness values
    probabilities = fitness_values / np.sum(fitness_values)
    selected_indices = np.random.choice(len(population), size=(len(population)//2), replace=True, p=probabilities)
    offspring = population[selected_indices]
    return offspring

In [28]:
"""
s = M // 2 

# Select the indices of the fittest strings based on their fitness values
fittest_indices = np.argsort(fitness_values)[::-1][:s]

# Select the fittest strings from the population matrix
fittest_strings = POP[fittest_indices]

fittest_strings
"""

'\ns = M // 2 \n\n# Select the indices of the fittest strings based on their fitness values\nfittest_indices = np.argsort(fitness_values)[::-1][:s]\n\n# Select the fittest strings from the population matrix\nfittest_strings = POP[fittest_indices]\n\nfittest_strings\n'

Crossover

In [29]:
def crossover_2(parents):
    # Perform uniform crossover
    num_attributes = parents.shape[1]
    offspring = np.empty_like(parents)
    for i in range(len(parents) // 2):
        parent1, parent2 = parents[i * 2], parents[i * 2 + 1]
        crossover_points = np.random.choice(num_attributes, num_attributes // 2, replace=False)
        child1, child2 = parent1.copy(), parent2.copy()
        for point in crossover_points:
            child1[point], child2[point] = child2[point], child1[point]
        offspring[i * 2], offspring[i * 2 + 1] = child1, child2
    return offspring

In [31]:
def crossover(fittest_strings):
    s = fittest_strings.shape[0]  # Number of fittest strings
    offspring_matrix = np.zeros_like(fittest_strings)

    # Perform uniform crossover for each pair of parent strings
    for i in range(0, s, 2):  # Step 2 (select pairs of parent strings)
        # Randomly select half of the attributes to participate in crossover
        crossover_indices = random.sample(range(K), K // 2)  # Indices of attributes to participate in crossover

        # Perform crossover for the selected attributes
        for j in crossover_indices:
            # Swap the substrings (attributes) between the parent strings to produce offspring
            offspring_matrix[i, j*(L[j]-1):(j+1)*(L[j]-1)] = fittest_strings[i+1, j*(L[j]-1):(j+1)*(L[j]-1)]
            offspring_matrix[i+1, j*(L[j]-1):(j+1)*(L[j]-1)] = fittest_strings[i, j*(L[j]-1):(j+1)*(L[j]-1)]

    return offspring_matrix
    # Display the offspring matrix
    #print("Offspring matrix after crossover:")
    #print(offspring_matrix)

Mutation

In [33]:
def mutation(offspring_matrix):
    # Define the mutation probability
    mutation_probability = 0.1  # Probability of mutation (adjust as needed)

    # Initialize the mutated offspring matrix
    mutated_offspring_matrix = np.copy(offspring_matrix)

    # Perform mutation for each string in the offspring matrix
    for i in range(mutated_offspring_matrix.shape[0]):  # Iterate over each string
        # Check if mutation should occur for the current string
        if random.random() < mutation_probability:
            # Randomly pick one attribute to mutate
            attribute_index = random.randint(0, K - 1)  # Randomly select an attribute index

            # Randomly pick a new level for the selected attribute
            new_level_index = random.randint(0, L[attribute_index] - 2)  # Randomly select a new level index

            # Determine the start and end indices of the selected attribute in the string
            start_index = sum(L[j] - 1 for j in range(attribute_index))
            end_index = start_index + L[attribute_index] - 1

            # Set the new level for the selected attribute in the string
            mutated_offspring_matrix[i, start_index:end_index] = 0  # Reset the attribute to all zeros
            mutated_offspring_matrix[i, start_index + new_level_index] = 1  # Set the new level to 1

    return mutated_offspring_matrix

    # Display the mutated offspring matrix
#    print("Mutated offspring matrix:")
#    print(mutated_offspring_matrix)

In [34]:
#mutated_offspring_matrix.shape

Implementing Stopping Rule and Starting GA loop

In [49]:
# Main loop for genetic algorithm iterations
while True:
    # Increment the generation count
    t += 1
   
    # Evaluate fitness
    fitness_vals = fitness(POP)
    fittest_strs = reproduction(POP, fitness_vals)
    offsprings = crossover(fittest_strs)
    mutated_offsprings = mutation(offsprings)

    # Calculate the fitness of the top three strings
    fitness_values_sorted = np.argsort(-fitness_vals)
    top_strings_fitness = fitness_values_sorted[:3]  # Assuming fitness_values_sorted contains sorted fitness values
    
    # Calculate the moving average of the fitness over five generations
    moving_avg_fitness[t % 5] = np.mean(top_strings_fitness)
    if t >= 5:
        avg_fitness = np.mean(moving_avg_fitness)
        
        # Calculate 2% of the fitness of the three best strings
        threshold_fitness = np.mean(top_strings_fitness) * (threshold_percent_of_best / 100)
        
        # Check if the moving average is less than the threshold
        if avg_fitness < threshold_fitness:
            print("Stopping criterion met. Algorithm terminated.")
            break
    
    # Display progress and other information
    print(f"Generation {t}: Moving Average Fitness = {avg_fitness:.2f}, Threshold Fitness = {threshold_fitness:.2f}")

NameError: name 'avg_fitness' is not defined

In [69]:
def genetic_algo(generation, t, moving_avg_fitness, threshold_percent_of_best, num_consecutive_stable_generations_required):
    # Increment the generation count
    t += 1
   
    # Evaluate fitness
    fitness_vals = fitness(generation)
    #print(fitness_vals)
    fittest_strs = reproduction(generation, fitness_vals)
    #print(fittest_strs)
    offsprings = crossover(fittest_strs)
    mutated_offsprings = mutation(offsprings)

    # Calculate the fitness of the top three strings
    fitness_values_sorted = np.argsort(-fitness_vals)
    top_strings_fitness = fitness_values_sorted[:3]  # Assuming fitness_values_sorted contains sorted fitness values

    # Calculate 2% of the fitness of the three best strings
    threshold_fitness = np.mean(top_strings_fitness) * (threshold_percent_of_best / 100)

    # Display progress and other information

    #print(f"Generation {t}: Moving Average Fitness = {avg_fitness:.2f}, Threshold Fitness = {threshold_fitness:.2f}")  
    print(f"Generation {t}: Threshold Fitness = {threshold_fitness:.2f}")   

    # Assume some stopping condition to break out of the loop
    if t >= 10:
        print("Stopping criterion met. Algorithm terminated.")
        exit
    else:
        genetic_algo(mutated_offsprings, t, 0, 2, 5)
    
    """
    # Calculate the moving average of the fitness over five generations
    moving_avg_fitness[t % 5] = np.mean(top_strings_fitness)
    if t >= 5:
        avg_fitness = np.mean(moving_avg_fitness)
        
        # Calculate 2% of the fitness of the three best strings
        threshold_fitness = np.mean(top_strings_fitness) * (threshold_percent_of_best / 100)
        
        # Check if the moving average is less than the threshold
        if avg_fitness < threshold_fitness:
            print("Stopping criterion met. Algorithm terminated.")
            exit
        else:
            print(f"Generation {t}: Moving Average Fitness = {avg_fitness:.2f}, Threshold Fitness = {threshold_fitness:.2f}")    # Display progress and other information
            genetic_algo(mutated_offsprings)
    """

In [70]:
# Initialize variables for stopping rule
t = 0
moving_avg_fitness = [float('inf')] * 5  # Initialize with large values for the moving average
threshold_percent_of_best = 2  # Set the threshold as 2% of the fitness of the three best strings
num_consecutive_stable_generations_required = 5  # Set the number of consecutive stable generations required

genetic_algo(POP, t, moving_avg_fitness, threshold_percent_of_best, num_consecutive_stable_generations_required)

Generation 1: Threshold Fitness = 0.69


IndexError: index 25 is out of bounds for axis 0 with size 25